---
apt_default_apps:
  - snapd
  - neovim
  - terminator
  - git
  - firefox
  - nextcloud-desktop
  - vagrant
  - python3-pip
  - build-essential
  - dkms
  - unzip
  - virtualbox
  - meld
  - net-tools
  - keepass2
  - tlp
  - tlp-rdw
  - gparted
  - wireguard
  - lm-sensors
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin
  - android-sdk-platform-tools
  - android-sdk-platform-tools-common
  - dnsutils
  - imagemagick

