---
- name: My Machine
  hosts: 127.0.0.1
  connection: local
  become: true
  gather_facts: false
  tasks:
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
        autoremove: yes
        update_cache: yes
    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist
    - name: install apt useful packages
      ansible.builtin.apt:
        pkg:
          - snapd
          - neovim
          - terminator
          - git
          - firefox
          - nextcloud-desktop
          - vagrant
          - python3-pip
          - build-essential
          - dkms
          - unzip
          - virtualbox
            #          - virtualbox-ext-pack
          - meld
    - name: install snap useful apps
      snap:
        name: 
          - spotify
          - bitwarden
          - canonical-livepatch
          - doctl
            # - lens
          - teams-for-linux
          - telegram-desktop
          - thunderbird
          - zoom-client
          - slack
        state: present
    - name: install classic apps via snap
      snap:
        name: 
          - code
          - skype
          - aws-cli
        classic: yes
    - name: install pip useful packages
      ansible.builtin.pip:
        name: grip
