---
- name: My Machine
  hosts: 127.0.0.1
  connection: local
  become: true
  gather_facts: false
  tasks:
    - name: Allow everything and enable UFW
      ufw:
        state: enabled
        policy: deny
        logging: on
